### ISSUE TITLE
Old Japanese laundry symbols

### ISSUE THREAD

**Issue by vavavr00m** [gbgabo/laundry-symbols#4]
Someone recently asked me what the (old) Japanese laundry symbols mean and tried to find them but most guides don't have them.

Ref: 
https://www.japanlivingguide.net/dailylife/life/dry-cleaning/
https://egl.livejournal.com/11980702.html
https://www.sbs-zipper.com/blog/japan-implements-new-clothing-care-symbols-with-iso-standards-from-december-1-2016/

Will they be included?

**Comment by gbgabo** [comment]
Hey @vavavr00m, whats up?

Sorry for the months late answer. I'm still not used to github notifications.

It's great you leaving a request because that's exactly the kind of symbols I need to add to truly make the page useful.

I'm not sure if you speak japanese, but in the chance of you finding more content in japanese that contains those symbols in **svg graphics**, I would highly appreciate of you sharing.

From the end of this year to the start the next one I'll have more free time to add these new symbols. I'll keep issue updated.

Thank again you for your request!

**Comment by gbgabo** [comment]
## TODO

- [ ] Find (or create) svg graphics of symbols
- [ ] Create dedicaded section for new category: Wringing
- [ ] Decide how to handle new different symbols of same description: Add as just another card item on the list or display as an alternative symbol on the same card (and how would that look)

**Comment by gbgabo** [comment]
@vavavr00m, a preview o the updated site can be viewed here: https://laundry-symbols-git-non-std-symbols-gbgabo.vercel.app, does it make sense?

It is only pending a full Brazilian and Japanese translation and it'll be ready for production.

**Comment by vavavr00m** [comment]
Some observations/suggestions below.

-----

⬜ When I select the US and non-standard filters, I get the Japanese icons. Normally, I would think that only US icons will contain only symbols from ASTM (American Society for Testing and Materials) if it makes sense.

-----

⬜ Some of the ironing icons on your website says "with a cloth" which could mean any cloth. Some Japanese websites used the term "pressing cloth" but some just say cloth. I'm not sure if you could use just about any cloth. Cloths with prints/dyes may leave a mark on the garment if you spray a bit of water on the garment and a hot iron pressed the slightly damp clothes if I'm not mistaken? I'm looking at this through the lens of someone who isn't familiar with ironing (could be a young person or an adult who is only just starting to learn to iron).

-----

⬜ The ironing temperature range from [this](https://web.archive.org/web/20191205060529/http://www.cfaccessories.com/information/japanese-washing-symbols/), [this](https://egl.livejournal.com/11980702.html) and [this](https://www.6shops.jp/carelabel) (multiple links for comparison) will be a great addition since "low," "medium," and "high" could be different from one country/manufacturer to another but I'm not certain which one was more accurate for the Japanese people at that time. I can only assume the description from [6shops](https://www.6shops.jp/carelabel) is for the newer icons more than the older ones.

![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/b6981215-2d09-40e1-a234-cfe77a8453b5)

-----

✅ [Note: Implemented as of 20240719]
This icon has a different description from other sources than [6shops](https://www.6shops.jp/carelabel). Other sources say "Hand wash," "Do not machine wash," and "Not machine washable" which sound vastly different from "**can be** washed by hand."

![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/b1a04192-1bfa-4ce8-bd82-b44cc2d497f7)

-----

The following symbols are missing:

✅ [Note: Implemented as of 20240719]
手洗イ30 中性 from [here](https://www.6shops.jp/carelabel) - probably means "Hand wash with a neutral detergent in water temperature of 30°C or less"
![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/11b1c256-265c-4993-84ce-aad8fda6886c)

⬜ [Note: As of 20240719, this was added but is missing the word "Gentle"]
 弱 30 from [here](https://web.archive.org/web/20191205060529/http://www.cfaccessories.com/information/japanese-washing-symbols/):
![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/d3d6a51e-859c-46e5-b300-e6dcbd0a7b46)

⬜ [Note: As of 20240719, this was added but temp is missing]
低 + (wave symbol at the bottom) from [here](https://web.archive.org/web/20191205060529/http://www.cfaccessories.com/information/japanese-washing-symbols/) - probably means "Should be ironed at a low temperature (between 80°C - 120°C) with a pressing cloth placed in between the iron and garment"
![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/f6ed5c8c-f8da-4fd8-ba81-07799d2f56f5)

⬜ [Note: As of 20240719, this was added but is missing "gentle" before wash]
弱 30 中性 from [here](https://egl.livejournal.com/11980702.html) or from this [pdf](https://www.coats.com/-/media/coats/information-hub/to-be-sorted/care-labels_tcm35-146052.pdf?rev=a04ed784df8a4f3e908cb26e26d1b05a) - probably means "Machine wash with a neutral detergant at gentle setting in water temperature of 30°C or less"
![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/27771cfa-2f9b-47e8-8946-e314ac72659b)

✅ [Note: Implemented as of 20240719]
40 ネット使用 from [here](https://carelabels.files.wordpress.com/2014/10/japanese-care-symbols.png) or from this [pdf](https://www.coats.com/-/media/coats/information-hub/to-be-sorted/care-labels_tcm35-146052.pdf?rev=a04ed784df8a4f3e908cb26e26d1b05a) - probably means "Machine wash inside a net in water temperature of 40°C or less"
![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/061844c0-acfb-4b01-a89a-3ec32e16b9d6)

-----

⬜ Have a separate entry for the legend and the just the symbol itself (just 2 symbols above this because the other one is already included). Legend:

![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/9b8e5508-c447-466a-ae82-e00da58a8ded)

-----

⬜ You may wanna separate Machine wash from Hand wash by placing them in their own subcategory under the category Washing to avoid any confusion.

-----

✅ [Note: Implemented as of 20240719]
弱 "Gentle" is missing from the description of 
![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/d21255ca-77f8-429f-be30-d3b1bd74113d)

See [this](https://en.montbell.jp/products/goods/washing/):

![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/15e6319e-1c8a-46b4-9c00-1b37da55f5f3)

-----

⬜ [Note: 20240719 I forgot was this was about. Probably uncertain whether to use PCE & HCS or resort to something more generic.
A quick Google returns that Petroleum-based solvents/solutions are hydrocarbon mixtures and Perchloroethylene is the systematic name of Tetrachloroethylene. The symbol ドライ only seems to have an inaccurate description. Please see comparison table below (all links were already mentioned previously):

![image](https://github.com/gbgabo/laundry-symbols/assets/4675132/d7a88281-7b41-4107-ae78-db8101c244c9)

-----

Some more Japanese terms [here](http://www.survivingnjapan.com/2011/11/guide-to-laundry-detergent-in-japan.html).

**Comment by gbgabo** [comment]
Wow! Fantastic addition on each topic, @vavavr00m

<hr/>

> _When I select the US and non-standard filters, I get the Japanese icons. Normally, I would think that only US icons will contain only symbols from ASTM (American Society for Testing and Materials) if it makes sense._

It makes. As I was making sure to find the full list of the most common international system (didn't know the name at the time), I then undertood [here](https://ginetex.de/wp-content/uploads/2018/06/V8_Technical_Booklet_web.pdf) that I was mixing an USA only labelling system.

`TODO` I will make sure to properly sort the ASTM system to the non-standard filter and review everything

<hr/>

> _Some of the ironing icons on your website says "with a cloth" which could mean any cloth. Some Japanese websites used the term "pressing cloth" but some just say cloth. I'm not sure if you could use just about any cloth. Cloths with prints/dyes may leave a mark on the garment if you spray a bit of water on the garment and a hot iron pressed the slightly damp clothes if I'm not mistaken? I'm looking at this through the lens of someone who isn't familiar with ironing (could be a young person or an adult who is only just starting to learn to iron)._

> _The ironing temperature range from [this](https://web.archive.org/web/20191205060529/http://www.cfaccessories.com/information/japanese-washing-symbols/), [this](https://egl.livejournal.com/11980702.html) and [this](https://www.6shops.jp/carelabel) (multiple links for comparison) will be a great addition since "low," "medium," and "high" could be different from one country/manufacturer to another but I'm not certain which one was more accurate for the Japanese people at that time. I can only assume the description from [6shops](https://www.6shops.jp/carelabel) is for the newer icons more than the older ones._

I share the same view. The idea is to consider someone with no base on how to apply the symbols to practice.

`TODO` My plan is to add an extra info section in the card with tips like cloth, presented visually like [chips](https://m3.material.io/components/chips/overview), but not interactive.

The same principle will be applied for the temperature range on the iron + washing symbols if needed.

<hr/>

Regarding incorrect text descriptions, I agree with them and I'll update as expected. The current texts are indeed half-baked, as I haven't still reviewed them one by one. Sorry for that.

<hr/>

> You may wanna separate Machine wash from Hand wash by placing them in their own subcategory under the category Washing to avoid any confusion.

I was pondering on relying on some subcategories, this may be the case.
You mean separate all the **machine shape** icons from the rest? Or just separate the hand wash icons from the rest?

<hr/>

Thanks a lot for your research @vavavr00m, you're contributing a lot! Great to have this kind of interaction

Edit: minor fix on absent quotation syntax.

**Comment by gbgabo** [comment]
Separating deliveries for each issue

### [This issue] Regarding old japanese laundry simbols

#### Finalizing first proper implementation of non-standard symbols
  
- [x] Make sure to proper separate ASTM and Legacy Japanese from GINETEX standard;
- [ ] Make sure all the symbols for each system is included;
- [ ] Review the best description for each symbol;
- [ ] Translate the updated list to portuguese and japanese;
- [ ] Make sure to mention @vavavr00m as a project contributor, do you mind?

###  [#6] Regarding other labelling systems + it's definitions:

#### Improvements over label description details, from tips to what system it belongs 

- [ ] add extra attribute on symbol object listing different systems the symbol can be found `systems: string[]`'; 
- [ ] add extra attribute to declare tips, useful for `temperature range` , `specific country`, `deprecated/old` or warnings. These will be displayed in the card like UI chips/tags;
- [ ] add subcategory attribute to list a smaller subset of that category: as in washing, varying from machine to _hand_ @vavavr00m?
- [ ] add more accurate filter based on system a symbol belongs to;

**Comment by vavavr00m** [comment]
@gbgabo Yeah it's nice to have an interaction about laundry symbols. Who would have thought I'd end up researching laundry symbols and talk about it with someone half way across the world. :-P Glad you made that checklist because I wrote one and didn't get the chance to send it.

> add subcategory attribute to list a smaller subset of that category: as in washing, varying from machine to hand @vavavr00m?

Yes.

> Make sure to mention @vavavr00m as a project contributor, do you mind?

No problem.

Not rush at all. This can be all be done next year. Wishing you enjoy the holidays!

**Comment by gbgabo** [comment]
Hello @vavavr00m, sending updates that I'm still alive!

Not only that but I've been working on the topics you've mentioned. I tried to fix typos and added missing symbols for each standard. 

Most of the time spent during the latest months were around restructuring the content (symbols) an translations for better maintainability and addition of translations and symbols such as Japanese.

The latest changes are available here: https://laundry-symbols-git-non-std-symbols-gbgabos-projects.vercel.app/

**Comment by vavavr00m** [comment]
Hey @gbgabo good to hear from you. I get updates of the commits and I know you've been busy ;-). Thanks for the heads up though. It's nice that you still remember me.

I'll have a look later but a quick glance tells me that the US and BR are rendered differently on a mobile browser compared to a PC browser since I see country flags on mobile and just text on PC. Is that normal?

**Comment by gbgabo** [comment]
@vavavr00m, as how its displayed currently, that's expected. It's relying on unicode symbols (the country flags emojis), and they are displayed differently depending the system you're on, as you probably have seen for emojis in general.

I have planned to add a unified look through icon collections on the project. I making sure to register the issue as I'll probably do this after the update related to card detailing and such. Thanks for the sharp view, mate!

**Comment by vavavr00m** [comment]
No worries and thank you for the update!

I also updated the [checklist](https://github.com/gbgabo/laundry-symbols/issues/4#issuecomment-1862352244) with some comments for the things that have been implemented. Additionally, I see some are yet to be implemented. Was it declined or will it be implemented in the future or do you need more clarity?
